### ISSUE TITLE
Issue when running setup_db.py

### ISSUE THREAD

**Issue by lmillischer** [jabrell/eutl_orm#3]
On Windows 10 Pro, when running the setup_db.py I receive the following error:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/xxx/PycharmProjects/eutl_orm/scripts/setup_db.py", line 22, in <module>
    dal = DataAccessLayer(**connectionSettings)
  File "C:\Users\xxx\PycharmProjects\eutl_orm\eutl_orm\dataAccessLayer.py", line 46, in __init__
    self.connect()
  File "C:\Users\xxx\PycharmProjects\eutl_orm\eutl_orm\dataAccessLayer.py", line 53, in connect
    self.metadata = MetaData(bind=self.engine, reflect=True)
TypeError: __init__() got an unexpected keyword argument 'reflect'

When changing this line:

https://github.com/jabrell/eutl_orm/blob/c5fac2c4e59dd7a3eb38f0045bcc2616beae0a36/eutl_orm/dataAccessLayer.py#L53

to: self.metadata = MetaData(bind=self.engine)

the problem does not appear any longer and I can populate the DB.

**Comment by jabrell** [comment]
Thanks for the report. Could you please let me know the version number of sqlalchemy?

**Comment by dibonaventura** [comment]
It's 1.4.27

Awesome package by the way, thanks for that!

**Comment by jabrell** [comment]
Thanks :) I will have look whats happing there and revise in the next update
